### PR TITLE
Recipes w/ wildcards

### PR DESCRIPTION
**Pull request by OrleansCF**
Will solve #7

### CODE REVIEW

**Comment by TheScree** [comment]
```
+          {
 +            "name": "Wood",
 +            "count": 1
 +          },
```
So when we look at the actual components within a recipe, this is too indestinct. I believe we need to alter our approach to something this like this;
```         
[{
   required_resource: "Wood",
   count: 1
},
{   
   wildcard_resource: "Stone",
   count: 1
},
{
   optional_component: "Vessel",
   count: 1
}]
```
Basically, by doing it this way, we can figure out quite easily if we need to do any recursive lookups; anything ending with a _component needs to be recursively processed, anything with _resource does not.

I think it'll save us a ton of headaches later on trying to figure this all out, and it'll condense the resources into a single aspect of the recipe file (meaning really easy for us to send a single variable to our recursive look up function.

**Comment by MichaelFedora** [comment]
I disagree @TheScree. Something more like:
```
{
  resource: wood,
  optional: false,
  wildcard: false,
  amount: 1
}```

Would he better imo. Also I thought "wildcard" means wood/ore/stone/etc, not just "wildcard wood" or something?

If it needs to be one of `n` types, tho, we could make `resource` into an array...

**Comment by Typ3Castt** [comment]
From a processing standpoint I like Michaels more. Just would be easier to work with using values. Resource as an array would work fine, even if it's single.

**Comment by MichaelFedora** [comment]
Sorry for dragging you around everywhere :(

We moved back to multiple files, but this time put the main and the variants into one folder:
I.E. instead of `/recipes/blacksmithing/<every single blacksmithing recipe>` do `/recipes/blacksmithing/metal_bar/<metal bar recipe + variants>`.

In addition put a variant flag on the variants, i.e.

```javascript
{
  "variants": ["variant1", "variant2"],
  "parent": null // thus is a parent
}
```

or

```javascript
{
  "variants": null,
  "parent": "parent" // thus is a variant
}
```

**Comment by CannibalVox** [comment]
Sorry to but in, but imo `success_chance` should be `success_cap` since the success chance is (100-difficulty)+assembly up to the cap.

Additionally, there are separate assembly & experimentation difficulties so that should be represented in the format.

**Comment by OrleansCF** [comment]
Pulled a new version of the spreadsheet, fixed a few things, and add number_created attribute. 

Added the script and spreadsheet used, which is a modified version of CytheS'. 

@MichaelFedora I decided to leave the schema largely the way it is, considering that it took me a bit to refactor the code to the previous request, and I don't see any significant advantages to reverting. Happy to discuss. 

@CannibalVox Understood, and whatever applications that build on this data can make the distinction, but for the JSON data it's important to use as close to game nomenclature as possible.

**Comment by OrleansCF** [comment]
@TheScree Please review, I believe this is ready to be pulled in.

**Pull request closed without merging**
